backend/bb/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('crm/', include('crm.urls', namespace='crm')),
    path('admin/', admin.site.urls),
    path('', include('web.urls', namespace='web')),
]

backend/web/urls.py
from django.urls import path

from . import views

app_name = 'web'

urlpatterns = [
    path('work-hours/', views.workhours, name='workhours'),
    path('', views.index, name='index'),
]

backend/templates/web/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'pages/index.css' %}">
    <title>"Борис Бритва" барбершоп</title>
</head>
<body class="body">
    <div class="page">
        <header class="header">
            <div class="header__title-box">
                <h1 class="header__title">
                    Борис Бритва
                </h1>
                <p class="header__subtitle">
                    барбершоп
                </p>
            </div>
            <div class="header__info-box">
                <p class="header__phone">
                    +7 (965) 565 33 33
                </p>
                <p class="header__text">
                    Пермь, ул. Сибирская, 10 (2 этаж)
                </p>
            </div>
        </header>
        <main class="main">

        {% include "web/nav.html" %}

            {% block content %}
                {# Содержимое блока #}
            {% endblock %}

        </main>
        <footer class="footer">


        </footer>
    </div>
</body>
</html>

backend/templates/web/index.html
{% extends "web/base.html" %}
{% block content %}
{% for master, entries in data.items %}
    <section class="dashboard">
        <h2 class="dashboard__title">
            {{ master.name }}
        </h2>
        <div class="dashboard__section">
            <ul class="dashboard__list">
                {% for entry in entries %}
                    <li class="dashboard__item dashboard__item_rows-{{ entry.step }}">
                        {{ entry.entry | date:"d.m.y - H:i" }}
                    </li>
                {% endfor %}
            </ul>
            <ul class="dashboard__list">
                {% for entry in entries %}
                    <li class="dashboard__item dashboard__item_rows-{{ entry.step }} dashboard__item_long">
                        Свободно
                    </li>
                {% endfor %}
            </ul>
        </div>
    </section>
{% endfor %}
{% endblock %}

backend/templates/web/nav.html
<nav class="menu">
    <a href="{% url 'web:index' %}" class="menu__link">Главная</a>
    <a href="/new" class="menu__link">Новая запись</a>
    <a href="{% url 'web:workhours' %}" class="menu__link">Рабочие часы</a>
    <a href="/entries" class="menu__link">Все записи</a>
    <a href="/masters" class="menu__link">Мастера</a>
    <a href="/profile" class="menu__link">Профиль</a>
</nav>

backend/templates/web/work-hours.html
{% extends "web/base.html" %}
{% block content %}
    <section class="desk">
        {% for master_id, dates in data.items %}
        <form action="{% url 'web:workhours' %}" method="post" class="form">
        {% csrf_token %}
            <h2 class="form__title"> {{ dates.0.name }} - расписание</h2>
            <label class="form__label">
                <span class="form__text">Начало дня:</span>
                <select id="time_begin" name="time_begin" class="form__select">
                    {% for w_time in times %}
                    <option class="form__select-option" value="{{ w_time }}">{{ w_time}}:00</option>
                    {% endfor %}
                </select>
            </label>
            <label class="form__label">
                <span class="form__text">Шаг записи:</span>
                <select id="step" name="step" class="form__select">
                    <option class="form__select-option" value="60">60 минут</option>
                    <option class="form__select-option" value="30">30 минут</option>
                    <option class="form__select-option" value="90">90 минут</option>
                    <option class="form__select-option" value="120">120 минут</option>
                </select>
            </label>
            <label class="form__label">
                <span class="form__text">Окончание работы:</span>
                <select id="time_end" name="time_end" class="form__select">
                    {% for w_time in times %}
                    <option class="form__select-option" value="{{ w_time }}">{{ w_time}}:00</option>
                    {% endfor %}
                </select>
            </label>
            {% for date_key, date_value in dates.1.items %}
            <label class="form__label">
                <span class="form__text">{{ date_value|date:"l (d E Y)"}}</span>
                <input class="form__checkbox" name="{{ date_key }}" value="{{ date_value|date:"Y-m-d" }}" type="checkbox">
            </label>
            {% endfor %}
            <input type="hidden" name="master" id="master" value="{{ master_id }}">
            <input type="submit" class="form__submit" value="Сформировать">
        </form>
        {% endfor %}
    </section>
{% endblock %}